
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: ``
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `data source=.;initial catalog=tong;user id=sa;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`

// -----------------------------------------------------------------------------------------
// Failed to read database schema - 无法打开登录所请求的数据库 "tong"。登录失败。 用户 'sa' 登录失败。
// -----------------------------------------------------------------------------------------


